ENT.Base = "base_ai" 
ENT.Type = "ai"
ENT.PrintName		= "Car Dealer"
ENT.Author			= "zachcheatham"
ENT.Category		= "KillerBeez"
ENT.Contact			= "N/A"
ENT.Purpose			= "N/A"
ENT.Instructions	= "Press E"
ENT.Spawnable		= true
ENT.AdminSpawnable		= true
ENT.AutomaticFrameAdvance = true
ENT.CarDealerType 	= "public"